spring.application.name=airportmanagementsystem

spring.datasource.url=jdbc:mysql://localhost:3306/airportdb
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true